### ISSUE TITLE
Usage in README is misleading

### ISSUE THREAD

**Issue by dbkaplun** [hashicorp/errwrap#4]
https://github.com/hashicorp/errwrap#basic-usage:
```go
	// ...
	if errwrap.Contains(err, ErrNotExist) {
		// Do something
	}
	// ...
```
`errwrap.Contains` type signature is [`func Contains(err error, msg string) bool`](https://github.com/hashicorp/errwrap/blob/7554cd9344cec97297fa6649b055a8c98c2a1e55/errwrap.go#L62). However `ErrNotExist` has the same name as [`os.ErrNotExist`](https://golang.org/pkg/os/#pkg-variables) and seems to contain an `error` based on naming. This is conflicting usage. Is the type signature wrong, or the usage documentation?

**Comment by mitchellh** [comment]
Usage documentation is probably misleading here, I was showing a message not existing rather than an `error` type. If you want to submit a quick PR I'd be happy to merge it. Thanks for pointing it out.
